Server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: edu-block-api
  datasource:
    url: ${DATA_SOURCE_URL:jdbc:postgresql://localhost:5432/edu}
    username: ${DATA_SOURCE_USERNAME:postgres}
    password: ${DATA_SOURCE_PASSWORD:4}
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration